### ISSUE TITLE
Feature request: Exit non-zero if a check fails

### ISSUE THREAD

**Issue by SpencerMalone** [cbrgm/promcheck#33]
Mentioned in the readme is the use case `Add promcheck to your CI/CD automation pipeline to run integration tests on your rules.`

I love the idea and would like to adopt it, but the fact that failing checks exit with exit code `0` makes it more frustrating that it should be.

**Comment by cbrgm** [comment]
Hey @SpencerMalone ! Valid point! Indeed, it would make sense to add an option to exit with exit code `1` in case no results were found for a given expression, especially for the CI/CD use case. 

I think a flag `--check.strict-mode` which will force promcheck to exit with `1` for the described scenario would make sense.
