### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by naveenbharadwaj-nc** [cbrgm/promcheck#53]
Hello, 
I use `checkResult, err := checker.CheckRuleGroup(convertRuleGroup(group))` to validate my prometheus rules. I have checked performance and it is bad. We have about 100 rules distributed in about 8-10 groups of prometheus rules. The checker takes almost 50 seconds to perform 100 rule checks. Can the performance be improved?
Using promcheck v.1.1.7

**Comment by cbrgm** [comment]
Hey thanks for your issue! Yeah rule validating is not parallelized. One improvement could be to check every group in it's own go routine and merge the results afterwards. I'll see what I can do!  😃

**Comment by naveenbharadwaj-nc** [comment]
Unfortunately, this is not possible because the next step is to perform some operations on valid and invalid groups. So the check has to complete fully before I proceed further. Please consider improving performance on checks.

**Comment by naveenbharadwaj-nc** [comment]
Could you please release the fix in new version?

**Comment by cbrgm** [comment]
Published now!
