### ISSUE TITLE
Support checking rules via API

### ISSUE THREAD

**Issue by metalmatze** [cbrgm/promcheck#8]
Right now promcheck needs to have a rules file available on disk to read and then check against.
It's not always the case, that one has the rules on disk (think Kubernetes environment).

It's possible to query rules and rule groups via the Prometheus API (http://localhost:9090/api/v1/rules) and promcheck could use that to get to the rules to then check against the Prometheus.

**Comment by cbrgm** [comment]
Implemented in #9 bundled with a lot of other features!
